---
title: "Li Wang's data: GTCB results from Gen Xu"
output: NULL
date: 05-26-2021
---

```{r setup, include=TRUE}
#setwd("~/Documents/Github/pvpDiallel/")
knitr::opts_knit$set(root.dir=normalizePath('../../'))
```


## GCTB SNP effects

```{r}
snp0 <- read.csv("cache/snpeff/eff_LAL_BLUP.csv")
snp0 <- snp0[1:3000,]

library(ggplot2)
p1 <- ggplot(snp0, aes(x=A1Frq, y=A1Effect)) +
  geom_point() +
    geom_smooth(method=loess) +
    xlab("Minor Allele Frequency") +
    ylab("SNP Effect") +
    ggtitle("LAL") +
    theme_classic() +
    #labs(color = "") +
    #scale_y_continuous(limits = c(-0.01, 1)) +
    #geom_vline(xintercept=0, linetype="dashed", color = "red") +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=18, face="bold"),
          #axis.text.x = element_text(angle = 20, hjust=0.6),
          legend.position = "none", 
          #axis.text.x = element_text(angle = 20, hjust=0.6),
          legend.title = element_text(size=18, face="bold"),
          legend.text = element_text(size=18))

p1
```


```{r}
snp0 <- read.csv("cache/snpeff/eff_LAU_BLUP.csv")
snp0 <- snp0[1:5000,]

p2 <- ggplot(snp0, aes(x=A1Frq, y=A1Effect)) +
  geom_point(alpha=0.5) +
    geom_smooth(method=loess) +
    xlab("Minor Allele Frequency") +
    scale_y_continuous(trans='log10')+
    ylab("SNP Effect") +
    ggtitle("LAU") +
    theme_classic() +
    #labs(color = "") +
    #scale_y_continuous(limits = c(-0.01, 1)) +
    #geom_vline(xintercept=0, linetype="dashed", color = "red") +
    theme(plot.title = element_text(size=20, face = "bold"), 
          axis.text=element_text(size=16, face="bold"),
          strip.text.x = element_text(size = 16, face = "bold"),
          axis.title=element_text(size=18, face="bold"),
          #axis.text.x = element_text(angle = 20, hjust=0.6),
          legend.position = "none", 
          #axis.text.x = element_text(angle = 20, hjust=0.6),
          legend.title = element_text(size=18, face="bold"),
          legend.text = element_text(size=18))

p2
```
